### ISSUE TITLE
Cross-build to support Scala 2.12

### ISSUE THREAD

**Issue by HaloFour** [Comcast/money#117]
Sirius currently doesn't support running with Scala 2.12 and due to some dependencies doesn't appear that it can be easily cross-built to support Scala 2.12.  This is preventing me from updating any of my other dependencies that have moved to supporting Scala 2.12, such as [money](https://github.com/Comcast/money/).  I'd like to explore what would be necessary cross-build Sirius for both Scala 2.11 and 2.12+.

**Comment by pauljamescleary** [comment]
@HaloFour thanks for the issue.  Money 0.9.0 does build to Scala 2.12.  I think maybe you mean to cross-build money to Scala 2.11?  Or perhaps this issue should be on the Sirius repository?

It _maybe_ possible to support Scala 2.11, I think setting the version and doing a build and see what pops out would be a simple small experiment.  However, it is better for everyone to move on and support 2.12 and the soon-to-be-released 2.13.

I imagine that Sirius would require some significant work to update to an akka + scala 2.12 compatible version.

**Comment by pauljamescleary** [comment]
I just checked out Sirius.  Seems like it currently runs akka 2.4.8.  2.4.20 is the latest 2.4.x and _should_ be compatible.  2.4.20 has a 2.12 version.

@HaloFour can you reach out to the Sirius folks (or submit a PR there) to just bump the version to 2.4.20 and then add the cross-build?  I don't run that

**Comment by HaloFour** [comment]
@pauljamescleary Oops, yes, I meant to open this issue on the sirius repo.  Sorry about that!
