### ISSUE TITLE
JMoney re-implimentation causes three logs to occur per successful span

### ISSUE THREAD

**Issue by ptravers** [Comcast/money#130]
https://github.com/Comcast/money/issues/107#issuecomment-537495229

**Comment by ptravers** [comment]
@hdzh does this also occur on span failure? Can you provide any additional context about the instrumented code?

**Comment by HaloFour** [comment]
@hdhz

Are you using the `@Traced` aspect with AspectJ or with Spring?

**Comment by hdzh** [comment]
It looks like an aspectj & spring aop problem. Paul got me fixed. Thank you @ptravers @HaloFour !

**Comment by ptravers** [comment]
@hdzh no problems. Glad it all worked out! If you feel like this would be an easy problem to come up against and the solution would be okay to post publicly. Would you mind posting the solution here for posterity?
