### ISSUE TITLE
Get ready for Public release

### ISSUE THREAD

**Issue by kristomasette** [Comcast/money#25]
- kill MavenSettings class
- Put in a ticket with Nexus to get our stuff into maven central
- Create our repo public
- Update "Contributing" docs to reflect our CI workflow
- Make sure we have License headers in all files 
- Check out the money kafka module, if we re-used code that was out there, it has to be properly attributed to the author
- Internal Release in preparation for deployment to maven central

**Comment by paulcleary** [comment]
- killed mavensettings
- have repo already in sonatype done
- made repo public
- license headers and contributing guide all present (may need some updating)
- removed integration tests from kafka

Also:
- setup travis ci
- setup codecov

Only thing remaining is to be able to publish to sonatype

**Comment by paulcleary** [comment]
Merged that last one that updated our build to publish signed to sonatype, we should be good here
