### ISSUE TITLE
LogEmitter output is not Splunk friendly

### ISSUE THREAD

**Issue by weggert** [Comcast/money#63]
There are some aspects of the LogEmitter that are not very friendly for Splunk.

Values for notes are not quoted, which causes Splunk to truncate the extracted value.  For example:
`[ userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0 ]`
winds up with this in Splunk:
`userAgent=Mozilla/5.0`

Also the field identifiers for span-name, span-id, trace-id, etc use `-`, which Splunk translates into a `_`.  That means that all searches need to make that translation.

For example, to search for a particular trace-id in Splunk, the query needs to be
`trace_id=<trace-id value>`

I would like to create an improved log format that is more Splunk friendly.  For backwards compatibility I think it may be better not to change the LogEmitter object.  Would creating a SplunkFriendlyLogEmitter object be a reasonable option?

**Comment by kristomasette** [comment]
Sounds totally reasonable to me!

**Comment by weggert** [comment]
Changing the underscores gets a bit more complicated than it would appear at first blush.  The logging keys for that are in money-http-client/src/main/scala/com/comcast/money/http/client/HttpTraceConfig.scala.

Also it would be great if we could have the duration logged in both ms and ns.  Most usages that I have come across are in ms and require a conversion from the provided ns value.

Having something like span_duration=<ms> span_duration_ns=<ns> http_call_duration=<ms> http_call_duration_ns=<ns> would be much easier to work with.

**Comment by weggert** [comment]
After looking at the LogEmitter a bit harder, it looks like we can accomplish everything we need by adding some configuration items to the existing class.

I put a pull request together with the additional configuration.
